/* JPKCom Desktop — icons: inline <symbol> sprite, icon(), logos, app tiles — © Jean Pierre Kolb — MIT License

   Icon ids:
     'ti-<name>'   Tabler outline icon (stroke based)
     'tif-<name>'  Tabler filled icon
     custom ids    hand-drawn glyphs from src/icons/custom.js (jpk, wc-*, tile-*)

   src/icons/tabler.js holds only the icons the sources use (generated by
   tools/build-icons.mjs — write ids out in full so the scanner finds them).
   A symbol enters the inline sprite the first time icon() asks for it, and
   icon() returns <svg><use href="#id"></svg>: one copy of each path in the
   document, coloured through currentColor. */

import { config } from './config.js';
import { SVGNS } from './env.js';
import { h } from './dom.js';
import tabler from '../icons/tabler.js';
import { symbols as customSymbols, logos as customLogos } from '../icons/custom.js';

const packs = new Map();        // id → definition
const logos = new Map(Object.entries(customLogos));
const placed = new Set();       // ids already in the sprite
const warned = new Set();
let sprite = null;

const OUTLINE = { fill: 'none', stroke: 'currentColor', 'stroke-linecap': 'round', 'stroke-linejoin': 'round' };
const FILLED = { fill: 'currentColor', stroke: 'none' };

/** Adds an icon pack ({ id: { k, e } | { vb, a, e } }). Existing ids stay unless override is set. */
export function addIcons(pack, { override = false } = {}) {
	for (const [id, def] of Object.entries(pack ?? {})) {
		if (!/^[a-z][a-z0-9-]*$/.test(id) || !def || !Array.isArray(def.e)) {
			console.warn(`[icons] skipped invalid icon '${id}'`);
			continue;
		}
		if (!packs.has(id) || override) packs.set(id, def);
	}
}

addIcons(tabler);
addIcons(customSymbols);

export const hasIcon = id => packs.has(id);

function ensureSprite() {
	if (sprite?.isConnected) return sprite;
	sprite = document.querySelector('svg.sprite');
	if (!sprite) {
		sprite = document.createElementNS(SVGNS, 'svg');
		sprite.setAttribute('class', 'sprite');
		sprite.setAttribute('aria-hidden', 'true');
		sprite.setAttribute('focusable', 'false');
		document.body.prepend(sprite);
	}
	return sprite;
}

function element(entry) {
	const [tag, attrs] = typeof entry === 'string' ? ['path', { d: entry }] : entry;
	const el = document.createElementNS(SVGNS, tag);
	for (const [k, v] of Object.entries(attrs)) el.setAttribute(k, v);
	return el;
}

function place(id) {
	if (placed.has(id)) return true;
	const def = packs.get(id);
	if (!def) return false;
	const symbol = document.createElementNS(SVGNS, 'symbol');
	symbol.setAttribute('id', id);
	symbol.setAttribute('viewBox', def.vb ?? '0 0 24 24');
	const attrs = def.a ?? (def.k === 'f' ? FILLED : OUTLINE);
	for (const [k, v] of Object.entries(attrs)) symbol.setAttribute(k, v);
	for (const entry of def.e) symbol.append(element(entry));
	ensureSprite().append(symbol);
	placed.add(id);
	return true;
}

/**
 * <svg class="i"><use href="#id"></svg>, decorative (aria-hidden). Give the
 * surrounding control an accessible name, never the icon.
 */
export function icon(id, cls = 'i') {
	const svg = document.createElementNS(SVGNS, 'svg');
	svg.setAttribute('class', cls);
	svg.setAttribute('aria-hidden', 'true');
	svg.setAttribute('focusable', 'false');
	if (!place(id)) {
		if (!warned.has(id)) {
			warned.add(id);
			console.warn(`[icons] unknown icon '${id}' — add it to the sources and run npm run icons`);
		}
		return svg;
	}
	const use = document.createElementNS(SVGNS, 'use');
	use.setAttribute('href', `#${id}`);
	svg.append(use);
	return svg;
}

/** Registers a logo builder: () → <svg>. */
export function addLogo(id, build) {
	if (typeof build === 'function') logos.set(id, build);
}

/** A fresh copy of a logo (own gradient ids), or null when there is none. */
export function logo(id = config.brand.logo) {
	const build = id ? logos.get(id) : null;
	if (!build) return null;
	try {
		return build();
	} catch (err) {
		console.warn(`[icons] logo '${id}' failed:`, err);
		return null;
	}
}

/** The brand glyph (monochrome, currentColor): config.brand.glyph or a neutral window icon. */
export const brandGlyph = (cls = 'i') => icon(config.brand.glyph && hasIcon(config.brand.glyph) ? config.brand.glyph : 'ti-app-window', cls);

/**
 * CSS value of a tint for --tint: a named tint ('blue' → var(--t-blue)) or a
 * pair of colours (['#56adff', '#1c62d6']). null for anything else.
 */
export function tintValue(tint) {
	if (typeof tint === 'string' && /^[a-z][a-z0-9-]*$/.test(tint)) return `var(--t-${tint})`;
	if (Array.isArray(tint) && tint.length === 2 && tint.every(c => /^#[0-9a-f]{6}$/i.test(c))) return `${tint[0]}, ${tint[1]}`;
	return null;
}

/**
 * The square app tile: the logo (app.logo: true → brand logo, or a logo id),
 * a short text mark (app.mark) or the icon (app.icon) on the tint gradient.
 */
export function tile(app, cls = '') {
	const lg = app.logo ? logo(app.logo === true ? config.brand.logo : app.logo) : null;
	const tint = tintValue(app.tint);
	return h('span', { class: ['tile', lg && 'tile-logo', cls], style: tint ? { '--tint': tint } : null },
		lg ?? (app.mark ? h('span', { class: 'tile-mark', 'aria-hidden': 'true', text: app.mark }) : icon(app.icon && hasIcon(app.icon) ? app.icon : 'ti-app-window')));
}
